### ISSUE TITLE
The new commit id added on dependency.sh broke the script

### ISSUE THREAD

**Issue by mpsbotelho** [HCK-CI/AutoHCK-Installer#15]
The commit id on the [dependency.sh](https://github.com/HCK-CI/AutoHCK-Installer/blob/main/dependencies.sh#L38) doesn't exist on the repository [AutoHCK](https://github.com/HCK-CI/AutoHCK.git)

**Comment by kostyanf14** [comment]
Hi @mpsbotelho,

Thanks for the report. This commit was outside of the master branch.
Already fixed.
